### ISSUE TITLE
less 参数有逗号怎么写

### ISSUE THREAD

**Issue by ada90** [fex-team/fis#218]
``` css
.font(@fontFamily:"Microsoft Yahei", "微软雅黑", Tahoma, Arial, STHeiti, sans-serif,@fontSize:1em,@color:#b0b0b0){
  font-family: @fontFamily;
  font-size: @fontSize;
  color:@color;
}
```
