### ISSUE TITLE
关于csssprites的单位问题

### ISSUE THREAD

**Issue by qdsang** [fex-team/fis#41]
移动开发中使用的em做为布局变量

``` css
.ico1{
    background: url($imgurl+"/x_01.png?__inline") no-repeat;
    background-size: (100em/20) (100em/20);
}
```

在csssprites中使用的是px作为单位，这有办法解决吗？

在?__sprites 后面加参数控制？
@xiangshouding
