### ISSUE TITLE
fis-spriter-csssprites在scale问题 

### ISSUE THREAD

**Issue by changexbc** [fex-team/fis#506]
使用 fis-spriter-cssspritesv0.3.0

```javascript
fis.config.set('settings.spriter.csssprites',{
 	 scale: 0.5
});
```
```css
.a1{
	background: url(icons/icon_01.gif?__sprite) no-repeat 0px 0px;
	width:32px;
	height:32px;
}.a2{
	background: url(icons/icon_02.gif?__sprite) no-repeat 0px 0px;
	width:32px;
	height:32px;
}.a3{
	background: url(icons/icon_03.gif?__sprite) repeat-y 0px 0px;
	width:320px;
	height:320px;
}.a4{
	background: url(icons/icon_04.png?__sprite) repeat-y 0px 0px;
	width:320px;
	height:320px;
}.a5{
	background: url(icons/icon_05.png?__sprite) repeat-x 0px 0px;
	width:320px;
	height:320px;
}.a6{
	background: url(icons/icon_06.png?__sprite) repeat-x 0px 0px;
	width:320px;
	height:320px;
}
```
![image](https://cloud.githubusercontent.com/assets/8199684/7812144/3ef96860-03e2-11e5-9efc-6bc3ce0dc6c8.png)

按照文档说明，css中没有写background-size,不知道是什么问题
不使用scale手写background-size也是同问题
