### ISSUE TITLE
如何配置css、js、包括css样式引入图片的路径啊

### ISSUE THREAD

**Issue by dongqc** [fex-team/fis#618]
如何配置css、js、包括css样式引入图片的路径啊

**Comment by xiangshouding** [comment]
不用配置，只需要安装相对路径或者相对于 FIS 项目根目录的绝对路径引入；

```
my-proj/a.js
my-proj/a/a.js
my-proj/b/b.css
my-proj/img/a.png
```
*a.js* 引入 *img/a.png*

```js
var img = __uri('./img/a.png');
```

*a/a.js* 引入 *img/a.png*

```js
// 1
var a = __uri('../img/a.png');
//2
var b = __uri('/img/a.png');
```

*b/b.css* 引入 *img/a.png*

```css
/* 1 */
#box {
  background-image: url('../img/a.png');
}

/* 2 */
#box_ {
  background-image: url('/img/a.png');
}
```
